#include "s21_string.h"

#if defined(__APPLE__)
#define UNKNOWN "Unknown error: "

static const char *errors_array[] = {
    "Undefined error: 0\n",
    "Operation not permitted\n",
    "No such file or directory\n",
    "No such process\n",
    "Interrupted system call\n",
    "Input/output error\n",
    "Device not configured\n",
    "Argument list too long\n",
    "Exec format error\n",
    "Bad file descriptor\n",
    "No child processes\n",
    "Resource deadlock avoided\n",
    "Cannot allocate memory\n",
    "Permission denied\n",
    "Bad address\n",
    "Block device required\n",
    "Resource busy\n",
    "File exists\n",
    "Cross-device link\n",
    "Operation not supported by device\n",
    "Not a directory\n",
    "Is a directory\n",
    "Invalid argument\n",
    "Too many open files in system\n",
    "Too many open files\n",
    "Inappropriate ioctl for device\n",
    "Text file busy\n",
    "File too large\n",
    "No space left on device\n",
    "Illegal seek\n",
    "Read-only file system\n",
    "Too many links\n",
    "Broken pipe\n",
    "Numerical argument out of domain\n",
    "Result too large\n",
    "Resource temporarily unavailable\n",
    "Operation now in progress\n",
    "Operation already in progress\n",
    "Socket operation on non-socket\n",
    "Destination address required\n",
    "Message too long\n",
    "Protocol wrong type for socket\n",
    "Protocol not available\n",
    "Protocol not supported\n",
    "Socket type not supported\n",
    "Operation not supported\n",
    "Protocol family not supported\n",
    "Address family not supported by protocol family\n",
    "Address already in use\n",
    "Can't assign requested address\n",
    "Network is down\n",
    "Network is unreachable\n",
    "Network dropped connection on reset\n",
    "Software caused connection abort\n",
    "Connection reset by peer\n",
    "No buffer space available\n",
    "Socket is already connected\n",
    "Socket is not connected\n",
    "Can't send after socket shutdown\n",
    "Too many references: can't splice\n",
    "Operation timed out\n",
    "Connection refused\n",
    "Too many levels of symbolic links\n",
    "File name too long\n",
    "Host is down\n",
    "No route to host\n",
    "Directory not empty\n",
    "Too many processes\n",
    "Too many users\n",
    "Disc quota exceeded\n",
    "Stale NFS file handle\n",
    "Too many levels of remote in path\n",
    "RPC struct is bad\n",
    "RPC version wrong\n",
    "RPC prog. not avail\n",
    "Program version wrong\n",
    "Bad procedure for program\n",
    "No locks available\n",
    "Function not implemented\n",
    "Inappropriate file type or format\n",
    "Authentication error\n",
    "Need authenticator\n",
    "Device power is off\n",
    "Device error\n",
    "Value too large to be stored in data type\n",
    "Bad executable (or shared library)\n",
    "Bad CPU type in executable\n",
    "Shared library version mismatch\n",
    "Malformed Mach-o file\n",
    "Operation canceled\n",
    "Identifier removed\n",
    "No message of desired type\n",
    "Illegal byte sequence\n",
    "Attribute not found\n",
    "Bad message\n",
    "EMULTIHOP (Reserved)\n",
    "No message available on STREAM\n",
    "ENOLINK (Reserved)\n",
    "No STREAM resources\n",
    "Not a STREAM\n",
    "Protocol error\n",
    "STREAM ioctl timeout\n",
    "Operation not supported on socket\n",
    "Policy not found\n",
    "State not recoverable\n",
    "Previous owner died\n",
    "Interface output queue is full"};

#elif defined(__linux__)
#define UNKNOWN "Unknown error "

static const char *errors_array[] = {
    "Success\n",
    "Operation not permitted\n",
    "No such file or directory\n",
    "No such process\n",
    "Interrupted system call\n",
    "Input/output error\n",
    "No such device or address\n",
    "Argument list too long\n",
    "Exec format error\n",
    "Bad file descriptor\n",
    "No child processes\n",
    "Resource temporarily unavailable\n",
    "Cannot allocate memory\n",
    "Permission denied\n",
    "Bad address\n",
    "Block device required\n",
    "Device or resource busy\n",
    "File exists\n",
    "Invalid cross-device link\n",
    "No such device\n",
    "Not a directory\n",
    "Is a directory\n",
    "Invalid argument\n",
    "Too many open files in system\n",
    "Too many open files\n",
    "Inappropriate ioctl for device\n",
    "Text file busy\n",
    "File too large\n",
    "No space left on device\n",
    "Illegal seek\n",
    "Read-only file system\n",
    "Too many links\n",
    "Broken pipe\n",
    "Numerical argument out of domain\n",
    "Numerical result out of range\n",
    "Resource deadlock avoided\n",
    "File name too long\n",
    "No locks available\n",
    "Function not implemented\n",
    "Directory not empty\n",
    "Too many levels of symbolic links\n",
    "Unknown error 41\n",
    "No message of desired type\n",
    "Identifier removed\n",
    "Channel number out of range\n",
    "Level 2 not synchronized\n",
    "Level 3 halted\n",
    "Level 3 reset\n",
    "Link number out of range\n",
    "Protocol driver not attached\n",
    "No CSI structure available\n",
    "Level 2 halted\n",
    "Invalid exchange\n",
    "Invalid request descriptor\n",
    "Exchange full\n",
    "No anode\n",
    "Invalid request code\n",
    "Invalid slot\n",
    "Unknown error 58\n",
    "Bad font file format\n",
    "Device not a stream\n",
    "No data available\n",
    "Timer expired\n",
    "Out of streams resources\n",
    "Machine is not on the network\n",
    "Package not installed\n",
    "Object is remote\n",
    "Link has been severed\n",
    "Advertise error\n",
    "Srmount error\n",
    "Communication error on send\n",
    "Protocol error\n",
    "Multihop attempted\n",
    "RFS specific error\n",
    "Bad message\n",
    "Value too large for defined data type\n",
    "Name not unique on network\n",
    "File descriptor in bad state\n",
    "Remote address changed\n",
    "Can not access a needed shared library\n",
    "Accessing a corrupted shared library\n",
    ".lib section in a.out corrupted\n",
    "Attempting to link in too many shared libraries\n",
    "Cannot exec a shared library directly\n",
    "Invalid or incomplete multibyte or wide character\n",
    "Interrupted system call should be restarted\n",
    "Streams pipe error\n",
    "Too many users\n",
    "Socket operation on non-socket\n",
    "Destination address required\n",
    "Message too long\n",
    "Protocol wrong type for socket\n",
    "Protocol not available\n",
    "Protocol not supported\n",
    "Socket type not supported\n",
    "Operation not supported\n",
    "Protocol family not supported\n",
    "Address family not supported by protocol\n",
    "Address already in use\n",
    "Cannot assign requested address\n",
    "Network is down\n",
    "Network is unreachable\n",
    "Network dropped connection on reset\n",
    "Software caused connection abort\n",
    "Connection reset by peer\n",
    "No buffer space available\n",
    "Transport endpoint is already connected\n",
    "Transport endpoint is not connected\n",
    "Cannot send after transport endpoint shutdown\n",
    "Too many references: cannot splice\n",
    "Connection timed out\n",
    "Connection refused\n",
    "Host is down\n",
    "No route to host\n",
    "Operation already in progress\n",
    "Operation now in progress\n",
    "Stale file handle\n",
    "Structure needs cleaning\n",
    "Not a XENIX named type file\n",
    "No XENIX semaphores available\n",
    "Is a named type file\n",
    "Remote I/O error\n",
    "Disk quota exceeded\n",
    "No medium found\n",
    "Wrong medium type\n",
    "Operation canceled\n",
    "Required key not available\n",
    "Key has expired\n",
    "Key has been revoked\n",
    "Key was rejected by service\n",
    "Owner died\n",
    "State not recoverable\n",
    "Operation not possible due to RF-kill\n",
    "Memory page has hardware error\n"};

#endif

char *s21_strerror(int errnum) {
  static char res[128] = {'\0'};

  if (errnum < 0 || errnum > ERR_COUNT) {
    s21_strcpy(res, "no error");
  } else {
    s21_strcpy(res, ((char *)errors_array[errnum]));
  }

  return res;
}